CREATE TABLE branches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    code VARCHAR(50),
    address VARCHAR(500),
    manager_id BIGINT,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('FIELD_EMPLOYEE', 'BRANCH_MANAGER', 'SUPER_ADMIN')),
    branch_id BIGINT,
    auth_provider_id VARCHAR(255),
    auth_type VARCHAR(50) DEFAULT 'BOTH' CHECK (auth_type IN ('GOOGLE_ONLY', 'LOCAL_ONLY', 'BOTH')),
    password_hash VARCHAR(255),
    is_active BOOLEAN DEFAULT TRUE,
    is_account_approved BOOLEAN DEFAULT FALSE,
    wage_type VARCHAR(20) CHECK (wage_type IN ('DAILY', 'HOURLY')),
    daily_rate DECIMAL(12,2),
    hourly_wage DECIMAL(12,2),
    total_leave_days_per_year DECIMAL(5,1) DEFAULT 0,
    remaining_leave_days DECIMAL(5,1) DEFAULT 0,
    carry_over_leave DECIMAL(5,1) DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (branch_id) REFERENCES branches(id)
);

CREATE TABLE daily_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    branch_id BIGINT,
    log_date DATE NOT NULL,
    start_time TIME,
    end_time TIME,
    hours_worked DECIMAL(5,2),
    category VARCHAR(50) NOT NULL CHECK (category IN (
        'NEW_FIBER_CONNECTION', 'SERVICE_MAINTENANCE', 'WIRE_REPAIR',
        'ROUTER_CONFIGURATION', 'CLIENT_SUPPORT', 'OFFICE_DUTY'
    )),
    location_description TEXT,
    location_lat DECIMAL(10,7),
    location_lng DECIMAL(10,7),
    work_description TEXT NOT NULL,
    photo_urls TEXT,
    assigned_task_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN (
        'PENDING', 'APPROVED', 'REJECTED', 'NEEDS_REVISION'
    )),
    reviewed_by BIGINT,
    review_comment TEXT,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    synced_at TIMESTAMP,
    reviewed_at TIMESTAMP,
    month_locked BOOLEAN DEFAULT FALSE,
    is_holiday_overtime BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (branch_id) REFERENCES branches(id),
    FOREIGN KEY (reviewed_by) REFERENCES employees(id)
);

CREATE TABLE leave_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    leave_type VARCHAR(20) NOT NULL CHECK (leave_type IN ('ANNUAL', 'SICK', 'PERSONAL')),
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    duration_days INT NOT NULL,
    reason TEXT NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')),
    reviewed_by BIGINT,
    review_comment TEXT,
    deducted_from_balance BOOLEAN DEFAULT FALSE,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (reviewed_by) REFERENCES employees(id)
);

CREATE TABLE tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assigned_by BIGINT NOT NULL,
    assigned_to BIGINT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    priority VARCHAR(20) DEFAULT 'MEDIUM' CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    status VARCHAR(20) DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED')),
    scheduled_date DATE,
    customer_name VARCHAR(255),
    customer_phone VARCHAR(50),
    customer_address VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    FOREIGN KEY (assigned_by) REFERENCES employees(id),
    FOREIGN KEY (assigned_to) REFERENCES employees(id)
);

CREATE TABLE monthly_lockouts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year_month VARCHAR(7) NOT NULL UNIQUE,
    lock_day INT DEFAULT 5,
    locked_at TIMESTAMP,
    locked_by BIGINT,
    is_unlocked BOOLEAN DEFAULT FALSE,
    unlocked_at TIMESTAMP,
    unlocked_by BIGINT,
    unlock_reason TEXT,
    FOREIGN KEY (locked_by) REFERENCES employees(id),
    FOREIGN KEY (unlocked_by) REFERENCES employees(id)
);

CREATE TABLE payroll_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    period_label VARCHAR(50) NOT NULL,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    days_worked INT DEFAULT 0,
    total_hours DECIMAL(8,2) DEFAULT 0,
    wage_rate_at_time DECIMAL(12,2) DEFAULT 0,
    overtime_hours DECIMAL(8,2) DEFAULT 0,
    overtime_rate_multiplier DECIMAL(3,2) DEFAULT 1.50,
    gross_pay DECIMAL(12,2) DEFAULT 0,
    deductions DECIMAL(12,2) DEFAULT 0,
    net_pay DECIMAL(12,2) DEFAULT 0,
    status VARCHAR(20) DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'CALCULATED', 'APPROVED', 'PAID')),
    paid_at TIMESTAMP,
    paid_by BIGINT,
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (paid_by) REFERENCES employees(id)
);

CREATE TABLE salary_advances (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    request_date DATE NOT NULL,
    reason TEXT,
    status VARCHAR(20) DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'DISBURSED', 'SETTLED')),
    approved_by BIGINT,
    approved_at TIMESTAMP,
    disbursed_at TIMESTAMP,
    is_settled BOOLEAN DEFAULT FALSE,
    settled_in_payroll_id BIGINT,
    notes TEXT,
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (approved_by) REFERENCES employees(id),
    FOREIGN KEY (settled_in_payroll_id) REFERENCES payroll_records(id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id BIGINT NOT NULL,
    type VARCHAR(50) NOT NULL,
    title VARCHAR(255) NOT NULL,
    body TEXT,
    is_read BOOLEAN DEFAULT FALSE,
    related_entity_type VARCHAR(50),
    related_entity_id BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (recipient_id) REFERENCES employees(id)
);

CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entity_type VARCHAR(50) NOT NULL,
    entity_id BIGINT NOT NULL,
    action VARCHAR(50) NOT NULL,
    actor_id BIGINT,
    previous_status VARCHAR(50),
    new_status VARCHAR(50),
    metadata TEXT,
    ip_address VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (actor_id) REFERENCES employees(id)
);

CREATE TABLE holidays (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    is_recurring_yearly BOOLEAN DEFAULT FALSE,
    overtime_applies BOOLEAN DEFAULT FALSE,
    created_by BIGINT,
    FOREIGN KEY (created_by) REFERENCES employees(id)
);

CREATE TABLE email_allow_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    added_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (added_by) REFERENCES employees(id)
);

ALTER TABLE branches ADD FOREIGN KEY (manager_id) REFERENCES employees(id);

CREATE INDEX idx_daily_logs_employee ON daily_logs(employee_id);
CREATE INDEX idx_daily_logs_status ON daily_logs(status);
CREATE INDEX idx_daily_logs_date ON daily_logs(log_date);
CREATE INDEX idx_leave_requests_employee ON leave_requests(employee_id);
CREATE INDEX idx_tasks_assignee ON tasks(assigned_to);
CREATE INDEX idx_notifications_recipient ON notifications(recipient_id);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_type, entity_id);
CREATE INDEX idx_payroll_employee ON payroll_records(employee_id);
