CREATE TABLE cash_collections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    customer_name VARCHAR(255) NOT NULL,
    customer_phone VARCHAR(50),
    customer_address VARCHAR(500),
    amount DECIMAL(12,2) NOT NULL,
    payment_method VARCHAR(50) NOT NULL CHECK (payment_method IN ('CASH', 'MOBILE_MONEY', 'BANK_TRANSFER')),
    service_type VARCHAR(50) NOT NULL CHECK (service_type IN ('NEW_CONNECTION', 'INSTALLATION', 'MAINTENANCE', 'REPAIR', 'OTHER')),
    description TEXT,
    location_lat DECIMAL(10,7),
    location_lng DECIMAL(10,7),
    photo_urls TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'NEEDS_REVISION')),
    reviewed_by BIGINT,
    review_comment TEXT,
    submitted_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP,
    FOREIGN KEY (employee_id) REFERENCES employees(id),
    FOREIGN KEY (reviewed_by) REFERENCES employees(id)
);

CREATE INDEX idx_cash_collections_employee ON cash_collections(employee_id);
CREATE INDEX idx_cash_collections_status ON cash_collections(status);
