ALTER TABLE employees ADD COLUMN IF NOT EXISTS token_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS mfa_enabled BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE employees ADD COLUMN IF NOT EXISTS mfa_code VARCHAR(255);
ALTER TABLE employees ADD COLUMN IF NOT EXISTS mfa_code_expiry TIMESTAMP;
